application: drnowebrtctest
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /manual/
  static_files: src/manual/index.html
  upload: src/manual/index.html
  secure: always

- url: /manual/(.+)/
  static_files: src/manual/\1/index.html
  upload: src/manual/(.+)/index.html

- url: /manual
  static_dir: src/manual
  secure: always

- url: /images
  static_files: src/images
  upload: src/images
  secure: always

- url: /css
  static_dir: src/css
  secure: always

- url: /
  static_files: src/vulcanized.html
  upload: src/vulcanized.html
  secure: always

- url: /.*
  script: testrtc.app
  secure: always
